name: count_down
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  calendar_date_picker2: ^1.1.8
  flutter:
    sdk: flutter
  intl: ^0.20.2
  row_date_picker: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
